markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Appendix's Blog
description: Leave Some Footprint
keywords: Jekyll Theme
url: http://appendix.pw
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html

#Author config
author:
    name: Appendix
    email: dszhenegyu@qq.com
    imageLink:http://imgdata.hoop8.com/1406/882-558930133.jpg
    simpleIntro: 屈云萌我爱你!
    detailIntro:
      <p>以前只在QQ空间上写过日志，看了许多大牛都有自己博客，买了域名，花了一两天弄懂了Jekyll之后决定开始创建一个自己的博客。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-weibo
    url: http://weibo.com/u/2560866771
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/dszhengyu

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
      
#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: 

duoshuo:
  config: false
  id: 
