markdown: kramdown
rouge: true
paginate: 8

safe:  false

#Site config
title: Appendix's Blog
description: Leave Some Footprint
keywords: Jekyll Theme
url: http://appendix.cc
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html

#Author config
author:
    name: Appendix
    email: dszhengyu@qq.com
    imageLink: /images/picture.jpg
    simpleIntro: Everything that kills me makes me feel alive.
    detailIntro:
      <p>小弱一个，技术贴少，新路历程多，轻喷。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/u/2560866771
  - class: icon-renren
    url: http://www.renren.com/474133926/profile
  - class: icon-github-alt
    url: http://github.com/dszhengyu

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: oilbeater
      url: http://oilbeater.com/
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html

#comment config
disqus:
  config: false
  id: 

duoshuo:
  config: true
  id: appendix
