markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Appendix's Blog
description: Leave Some Footprint
keywords: Jekyll Theme
url: http://appendix.pw
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html

#Author config
author:
    name: Appendix
    email: dszhenegyu@qq.com
    imageLink: http://tineye.com/search/show_match/99182b4dc6ff825531fd3c51f082d571103cdbb6/c6f1d3cd70ee9c06e41cd9d795b2bec53e17aa32b46a82482bd9dd193ab0eba8?m13=-0.014304&m21=0.000644721&m22=1.00016&m23=-0.0493795&m11=1.00016&m12=-0.000644721
    simpleIntro: 屈云萌我爱你
    detailIntro:
      <p>以前只在QQ空间上写过日志，看了许多大牛都有自己博客，买了域名，花了一两天弄懂了Jekyll之后决定开始创建一个自己的博客。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-weibo
    url: http://weibo.com/u/2560866771
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/dszhengyu

#Links
customLinks:
  - item:
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
      
#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: 

duoshuo:
  config: false
  id: 
